#ifndef ENGINEPLUGINTEST_GLOBAL_H
#define ENGINEPLUGINTEST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ENGINEPLUGINTEST_LIBRARY)
#  define ENGINEPLUGINTEST_EXPORT Q_DECL_EXPORT
#else
#  define ENGINEPLUGINTEST_EXPORT Q_DECL_IMPORT
#endif

#endif // ENGINEPLUGINTEST_GLOBAL_H
