#ifndef RIPPLEEFFECTS_GLOBAL_H
#define RIPPLEEFFECTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RIPPLEEFFECTS_LIBRARY)
#  define RIPPLEEFFECTS_EXPORT Q_DECL_EXPORT
#else
#  define RIPPLEEFFECTS_EXPORT Q_DECL_IMPORT
#endif

#endif // RIPPLEEFFECTS_GLOBAL_H
