#ifndef QTPLUGINSYSTEMCARDDYNAMIC_GLOBAL_H
#define QTPLUGINSYSTEMCARDDYNAMIC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTPLUGINSYSTEMCARDDYNAMIC_LIBRARY)
#  define QTPLUGINSYSTEMCARDDYNAMIC_EXPORT Q_DECL_EXPORT
#else
#  define QTPLUGINSYSTEMCARDDYNAMIC_EXPORT Q_DECL_IMPORT
#endif

#endif // QTPLUGINSYSTEMCARDDYNAMIC_GLOBAL_H
